{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "loggen.serviceAccountName" . }}
  labels:
    {{- include "loggen.labels" . | nindent 4 }}
{{- end }}
