replicaCount: 1

image:
  repository: ghcr.io/smana/loggen
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

affinity: {}

tolerations: []

topologySpreadConstraints: []

serviceAccount:
  create: true
  name: ""

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: null
