name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Set up cache for uv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install --editable .
          uv pip install .[test]
          uv pip install ruff mypy bandit docformatter

      - name: Lint with ruff
        run: .venv/bin/ruff check .

      - name: Type check with mypy
        run: .venv/bin/mypy loggen/

      - name: Run tests with pytest
        run: .venv/bin/pytest

      - name: Security check with bandit
        run: .venv/bin/bandit -r loggen/

      - name: Check docstring formatting with docformatter
        run: .venv/bin/docformatter --check --recursive loggen/
