name: Helm Lint and Template

on:
  pull_request:
    paths:
      - "helm/loggen/**"
  push:
    branches: [main]
    paths:
      - "helm/loggen/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Lint Helm chart
        run: helm lint helm/loggen

      - name: Template Helm chart
        run: helm template loggen helm/loggen --debug
